spring.application.name=foodWasteManagementApp
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${DB_NAME}
spring.data.mongodb.auto-index-creation=true
server.port=8080
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.authentication=DEBUG

# ===============================
# ACTUATOR ENDPOINT CONFIGURATION
# ===============================

# Custom Path
management.endpoints.web.base-path=${BASE_PATH}

# Expose ONLY required actuator endpoints (health,info,metrics,shutdown) in prod
management.endpoints.web.exposure.include=health,info,metrics,httpexchanges,shutdown

# # Health endpoint behavior
management.endpoint.health.show-details=always

# Enable environment info in /actuator/info
management.info.env.enabled=true

# ===============================
# HEALTH CHECKS
# ===============================

# Disk space health indicator
management.health.diskspace.enabled=true

# # MongoDB health (implemented custom)
management.health.mongodb.enabled=false

# ===============================
# HTTP REQUEST TRACING
# ===============================

# Record recent HTTP requests
management.httpexchanges.recording.enabled=true

# =====================
# Shutdown optimization
# =====================

# Instead of stopping immediately, it waits for task to finish
server.shutdown=graceful


# =======================
# For info API (Actuator)
# =======================
info.app.name=foodWasteManagementApp
info.app.version=1.0.0
info.app.description=An app to manage food waste effectively by donating to NGOs or waste collection centers
