spring.application.name=foodWasteManagementApp

# =========================
# EXCLUDE AUTO-CONFIGURATIONS
# =========================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration,org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# =========================
# CACHE CONFIG
# =========================
spring.cache.type=simple


# =========================
# MONGODB CONFIG
# =========================
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${DB_NAME}
spring.data.mongodb.auto-index-creation=true

# =========================
# PORT CONFIG
# =========================
server.port=8080

# =========================
# PROFILE CONFIG
# =========================
spring.profiles.active=${ACTIVE_PROFILE}

# =========================
# SPRING JSON PRETTIER
# =========================
spring.jackson.serialization.indent-output=true

# =========================
# LOGGING CONFIG
# =========================
logging.level.root=INFO
logging.level.com.abc.foodwastemanagement=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO    
logging.level.org.springframework.security.authentication=INFO

logging.file.name=${LOG_FILE}

# =========================
# JAVA MAIL CONFIG
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =========================
# REDIS CONFIG
# =========================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=${REDIS_TIMEOUT}

# =========================
# RATE LIMIT PROFILES
# =========================

# -------- AUTH --------
rate-limiting.profiles.AUTH.capacity=${AUTH_CAPACITY}
rate-limiting.profiles.AUTH.refill-interval-seconds=${AUTH_REFILL}
rate-limiting.profiles.AUTH.ttl-seconds=${AUTH_TTL}

# -------- READ -------- 
rate-limiting.profiles.READ.capacity=${READ_CAPACITY}
rate-limiting.profiles.READ.refill-interval-seconds=${READ_REFILL}
rate-limiting.profiles.READ.ttl-seconds=${READ_TTL}

# -------- WRITE --------
rate-limiting.profiles.WRITE.capacity=${WRITE_CAPACITY}
rate-limiting.profiles.WRITE.refill-interval-seconds=${WRITE_REFILL}
rate-limiting.profiles.WRITE.ttl-seconds=${WRITE_TTL}


# Unlimited profile (skip rate limiting)
rate-limiting.profiles.UNLIMITED.capacity=${UNLIMITED_CAPACITY}

# =========================
# ENDPOINT RULES
# =========================

rate-limiting.endpoints[0].path=/auth/**
rate-limiting.endpoints[0].method=POST
rate-limiting.endpoints[0].profile=AUTH
rate-limiting.endpoints[0].identity=IP

rate-limiting.endpoints[1].path=/donations/**
rate-limiting.endpoints[1].method=POST
rate-limiting.endpoints[1].profile=WRITE
rate-limiting.endpoints[1].identity=USER

rate-limiting.endpoints[2].path=/donations/**
rate-limiting.endpoints[2].method=PUT
rate-limiting.endpoints[2].profile=WRITE
rate-limiting.endpoints[2].identity=USER

rate-limiting.endpoints[3].path=/donations/**
rate-limiting.endpoints[3].method=GET
rate-limiting.endpoints[3].profile=READ
rate-limiting.endpoints[3].identity=USER

rate-limiting.endpoints[4].path=/donors
rate-limiting.endpoints[4].method=POST
rate-limiting.endpoints[4].profile=WRITE
rate-limiting.endpoints[4].identity=USER

rate-limiting.endpoints[5].path=/donors/**
rate-limiting.endpoints[5].method=GET
rate-limiting.endpoints[5].profile=READ
rate-limiting.endpoints[5].identity=USER

rate-limiting.endpoints[6].path=/donors/**
rate-limiting.endpoints[6].method=PUT
rate-limiting.endpoints[6].profile=WRITE
rate-limiting.endpoints[6].identity=USER

rate-limiting.endpoints[7].path=/manage-app/**
rate-limiting.endpoints[7].profile=UNLIMITED

rate-limiting.endpoints[8].path=/auth/google/**
rate-limiting.endpoints[8].method=GET
rate-limiting.endpoints[8].profile=AUTH
rate-limiting.endpoints[8].identity=IP

rate-limiting.endpoints[9].path=/v3/**
rate-limiting.endpoints[9].method=GET
rate-limiting.endpoints[9].profile=UNLIMITED
rate-limiting.endpoints[9].identity=IP

rate-limiting.endpoints[10].path=/swagger-ui/**
rate-limiting.endpoints[10].method=GET
rate-limiting.endpoints[10].profile=UNLIMITED
rate-limiting.endpoints[10].identity=IP


# =========================
# DEFAULT RATE LIMIT
# =========================

rate-limiting.defaults.profile=READ
rate-limiting.defaults.identity=USER


#################################
# KAFKA – COMMON
#################################
spring.kafka.bootstrap-servers=localhost:9092

#################################
# KAFKA – PRODUCER 
#################################
spring.kafka.producer.acks=1                    
spring.kafka.producer.retries=0               

# Not to wait for 60s when Kafka not available
spring.kafka.producer.properties.max.block.ms=200

# Serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#################################
# KAFKA – CONSUMER
#################################
spring.kafka.consumer.group-id=${KAFKA_TOPIC_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


#################################
# KAFKA – LISTENER
#################################
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.auto-startup=true

# Kafka logs
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR


# To retain the order of fields in the HTTPResponse
spring.jackson.mapper.sort-properties-alphabetically=false

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# OAuth2 config
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH2_REDIRECT_URI}


jwt_secret_key=${JWT_KEY} 

# Concurrency
server.tomcat.threads.max=200
server.tomcat.accept-count=100
server.tomcat.connection-timeout=20000