spring.application.name=foodWasteManagementApp
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${DB_NAME}
spring.data.mongodb.auto-index-creation=true
server.port=8080

# ===============================
# ACTUATOR BASE CONFIG
# ===============================
management.endpoints.web.base-path=${BASE_PATH}

# Expose ONLY what is needed publicly
management.endpoints.web.exposure.include=health,info

# Health endpoint
management.endpoint.health.show-details=never

# App info
management.info.env.enabled=true

# ===============================
# HEALTH CHECKS
# ===============================
management.health.diskspace.enabled=true
management.health.mongodb.enabled=false

# ===============================
# SHUTDOWN 
# ===============================
server.shutdown=graceful
# management.endpoint.shutdown.enabled=false

# ===============================
# OBSERVABILITY (DISABLED)
# ===============================
management.httpexchanges.recording.enabled=false

# ===============================
# LOGGING 
# ===============================
logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.mongodb.driver=WARN
logging.level.com.abc.foodwastemanagement=INFO


# Enable graceful shutdown endpoint
# management.endpoint.shutdown.access=unrestricted


# =======================
# For info API (Actuator)
# =======================
info.app.name=foodWasteManagementApp
info.app.version=1.0.0
info.app.description=An app to manage food waste effectively by donating to NGOs or waste collection centers

