package com.abc.foodwastemanagement.enums;

public enum ErrorCode {

    // User
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,

    // Collection Center
    COLLECTION_CENTER_NOT_FOUND,

    // Donation
    DONATION_NOT_FOUND,
    DONATION_ALREADY_COLLECTED,
    PAST_PICKUP_DATE,

    // Donor
    DONOR_NOT_FOUND,

    // Authorization / Request
    UNAUTHORIZED_ACTION,
    INVALID_REQUEST,
    OPERATION_NOT_ALLOWED,
    INVALID_CREDENTIALS,
    USER_DISABLED,
    USER_LOCKED,

    // Password reset
    INVALID_PASSWORD_RESET_TOKEN,
    PASSWORD_RESET_TOKEN_ALREADY_USED,
    PASSWORD_RESET_TOKEN_EXPIRED,

    // Email
    EMAIL_NOT_VERIFIED,
    EMAIL_NOT_FOUND,
    INVALID_EMAIL_VERIFICATION_TOKEN,
    EMAIL_VERIFICATION_TOKEN_USED,
    EMAIL_VERIFICATION_TOKEN_EXPIRED,
    EMAIL_VERIFICATION_NOT_REQUIRED,

    // Rate limit
    REQUEST_LIMIT_EXCEEDED,

    // Notifications
    NOTIFICATION_NOT_FOUND,

    // OAuth2
    AUTHENTICATION_FAILED,

    // System
    INTERNAL_ERROR
}

